# Generated by Django 3.0.7 on 2020-07-01 00:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(db_index=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(default=datetime.datetime.now)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.App')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ended_at', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.App')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.Visitor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('E', 'Event'), ('A', 'Action')], db_index=True, max_length=1)),
                ('activity_type', models.CharField(db_index=True, max_length=255)),
                ('properties', models.TextField(blank=True, default=None, null=True)),
                ('occured_at', models.DateTimeField(db_index=True)),
                ('device_name', models.CharField(db_index=True, max_length=255)),
                ('device_os', models.CharField(db_index=True, max_length=255)),
                ('package_name', models.CharField(db_index=True, max_length=255)),
                ('package_version', models.CharField(db_index=True, max_length=255)),
                ('package_build', models.CharField(max_length=255)),
                ('remote_ip', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.App')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.Session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.Visitor')),
            ],
            options={
                'verbose_name_plural': 'Activity',
            },
        ),
    ]
