# Generated by Django 3.0.8 on 2020-07-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femtolytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='remote_ip',
        ),
        migrations.AlterField(
            model_name='app',
            name='package_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
