# Generated by Django 3.0.8 on 2020-07-31 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('femtolytics', '0002_auto_20200722_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='first_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_visitor', to='femtolytics.Session'),
        ),
    ]
