# Generated by Django 3.0.8 on 2020-07-31 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('femtolytics', '0002_auto_20200722_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
