# Generated by Django 3.0.8 on 2020-08-01 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('femtolytics', '0004_visitor_first_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(db_index=True, max_length=128)),
                ('first_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activities', models.ManyToManyField(to='femtolytics.Activity')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femtolytics.App')),
                ('sessions', models.ManyToManyField(to='femtolytics.Session')),
            ],
            options={
                'verbose_name_plural': 'Crashes',
                'unique_together': {('signature', 'app')},
            },
        ),
    ]
